dist:     trusty
language: java

addons:
  apt_packages:
    - php5-cli

notifications:
  email:  false

matrix:
  include:
    - env: IDEA_VERSION="IU-2021.1.2" PHP_PLUGIN_VERSION="211.7442.50"
      jdk: oraclejdk11
    - env: IDEA_VERSION="IU-2020.3.4" PHP_PLUGIN_VERSION="203.5981.175"
      jdk: oraclejdk11
    - env: IDEA_VERSION="IU-2020.2.4" PHP_PLUGIN_VERSION="202.8194.11"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2020.1.4" PHP_PLUGIN_VERSION="201.8743.1"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2019.3.4" PHP_PLUGIN_VERSION="193.6911.15"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2019.2.4" PHP_PLUGIN_VERSION="192.7142.51"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2019.1.4" PHP_PLUGIN_VERSION="191.8026.56"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2018.3.6" PHP_PLUGIN_VERSION="183.5429.47"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2018.2.8" PHP_PLUGIN_VERSION="182.4892.16"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2018.1.8" PHP_PLUGIN_VERSION="181.5281.35"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2017.3.6" PHP_PLUGIN_VERSION="173.4674.46"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2017.2.7" PHP_PLUGIN_VERSION="172.4155.41"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2017.1.6" PHP_PLUGIN_VERSION="171.4694.2"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2016.3.8" PHP_PLUGIN_VERSION="163.10504.2"
      jdk: oraclejdk8
    - env: IDEA_VERSION="IU-2016.2.5" PHP_PLUGIN_VERSION="162.1628.23"
      jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - java -version && php -v
  - chmod +x gradlew
  - "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
  - "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"

script:
  - php .travis/rules-list-check.php
  - php .travis/orphaned-fixtures-check.php
  - php .travis/fixer-verifies-disposed-project-check.php
  - php .travis/get-project-traverse-free-check.php
  - php .travis/verify-visitors-stubs.php
  - php .travis/verify-visitors-definitions.php
  - php .travis/verify-messages-prefixing.php
  - php .travis/verify-qickfix-title-prefixing.php
  - php .travis/verify-discovered-values-cleanup.php
  - php .travis/fix-short-and-display-names.php
  - ./gradlew check buildPlugin
